version: '3'

services:
  db:
    container_name: cloud_backend_db
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env
    volumes:
      - cloud_db_data:/var/lib/mysql      
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 30
  
  backend:
    container_name: cloud_backend_API
    build: ./backend
    restart: always
    env_file:
      - .env
    volumes:
      - cloud_backend_storage:/app/DocManageSystem/store
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: cloud_frontend
    build: ./frontend
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy    

  gateway:
    container_name: cloud_backend_gateway
    build: ./gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    depends_on:
      - frontend
      - backend

volumes:
  cloud_db_data:
  cloud_backend_storage: